version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spoker-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spoker-frontend
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000 
